##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.4.0-B60] date: [Fri Sep 13 15:46:34 CST 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32l5_non_secure_bsp


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32l5xx_it.c \
Core/Src/stm32l5xx_hal_msp.c \
Core/Src/stm32l5xx_hal_timebase_tim.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_utils.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_exti.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_adc.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_adc_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ramfunc.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_icache.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_ucpd.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_gpio.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_dma.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pcd.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pcd_ex.c \
STM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_usb.c \
Core/Src/system_stm32l5xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
hal/src/hal_gpio.c \
hal/src/hal_uart.c \
hal/src/hal_irq.c \
hal/src/hal_mcu.c \
hal/src/hal_flash.c \
hal/src/hal_cache.c \
osal/src/osal_task.c \
osal/src/osal_mutex.c \
osal/src/osal_sem.c \
osal/src/osal_queue.c \
osal/src/osal_sched.c \
osal/src/osal_heap.c \
osal/src/osal_log.c \
osal/src/osal_hooks.c \
osal/src/osal_utils.c \
FreeRTOS/list.c \
FreeRTOS/queue.c \
FreeRTOS/tasks.c \
FreeRTOS/timers.c \
FreeRTOS/event_groups.c \
FreeRTOS/stream_buffer.c \
FreeRTOS/portable/MemMang/heap_4.c \
FreeRTOS/portable/GCC/ARM_CM33_NTZ/non_secure/port.c \
FreeRTOS/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l552xx.s

# ASM sources
ASMM_SOURCES =


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
# Fallback: on Windows, if neither GCC_PATH nor PATH is set up (e.g. running
# `make` without `source prj.cfg`), auto-detect the downloaded toolchain.
ifndef GCC_PATH
ifeq ($(OS),Windows_NT)
_WIN_GCC_PATH := C:/opt/cross_compile/arm-gnu-toolchain-13.3.rel1-mingw-w64-i686-arm-none-eabi/bin
ifneq ($(wildcard $(_WIN_GCC_PATH)/$(PREFIX)gcc.exe),)
GCC_PATH := $(_WIN_GCC_PATH)
endif
endif
endif
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m33

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32L552xx


# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ISTM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Inc \
-ISTM32CubeL5/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy \
-ISTM32CubeL5/Drivers/CMSIS/Include \
-ISTM32CubeL5/Drivers/CMSIS/Device/ST/STM32L5xx/Include \
-Ihal/include \
-Iosal/include \
-Iconfig \
-IFreeRTOS/include \
-IFreeRTOS/portable/GCC/ARM_CM33_NTZ/non_secure

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L552xE_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***